---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {ENVIRONMENT_IDENTIFIER}
  name: ows-core-deployment
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: ows-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ows-core
    spec:
      containers:
        - name: ows-core
          image: {DOCKER_IMAGE_PLACEHOLDER}
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            httpGet:
              port: 8080
              path: /api/actuator/health
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_TAG
              value: "14"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: DATABASE_USER
            - name: DATABASE_URL_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: DATABASE_URL_SCHEMA
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: DATABASE_PASS
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: DATABASE_NAME
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: DATABASE_HOST
            - name: BITCOIN_RPC_HOST
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: BITCOIN_RPC_HOST
            - name: BITCOIN_RPC_PORT
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: BITCOIN_RPC_PORT
            - name: BITCOIN_RPC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: BITCOIN_RPC_USERNAME
            - name: BITCOIN_RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: BITCOIN_RPC_PASSWORD
            - name: ELASTIC_APM_ENABLED
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: ELASTIC_APM_ENABLED
            - name: BITCOIN_ENABLED
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: BITCOIN_ENABLED
            - name: BITCOIN_NETWORK
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: BITCOIN_NETWORK
            - name: LITECOIN_ENABLED
              valueFrom:
                secretKeyRef:
                  name: ows-core-secrets
                  key: LITECOIN_ENABLED
---
apiVersion: v1
kind: Service
metadata:
  namespace: {ENVIRONMENT_IDENTIFIER}
  name: ows-core-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: ows-core
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {ENVIRONMENT_IDENTIFIER}
  name: ows-core-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/certificate-arn: {SSL_CERT_ARN}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/healthcheck-path: "/api/actuator/health"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ows-core-service
                port:
                  name: http