apiVersion: v1
kind: Namespace
metadata:
  name: crypto-wallet
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crypto-wallet
  name: secrets-crypto-wallet
type: Opaque
stringData:
  DATABASE_HOST: "quips-cluster.cxdsw.mongodb.net"
  DATABASE_USER: quipsAdmin
  DATABASE_PASS: CJ8DKGA0XNCxFQra
  DATABASE_NAME: staking_db
  BITCOIN_RPC_HOST: "3.68.186.140"
  BITCOIN_RPC_PORT: "18332"
  BITCOIN_RPC_USERNAME: bitcoinNode
  BITCOIN_RPC_PASSWORD: bitcoinPassword
