# Service Config
server:
  address: 0.0.0.0
  port: ${PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /api
  forward-headers-strategy: native

# GraphQL
graphql:
  servlet:
    enabled: true
    mapping: /graphql
    subscriptions:
      websocket:
        path: /subscriptions
    corsEnabled: false

graphiql:
  enabled: true
  endpoint: /api/graphql
  mapping: /graphiql
  cdn:
    enabled: false
    version: latest

# Spring Config
spring:
  data:
    mongodb:
      uri: ${DATABASE_URL_SCHEMA}://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${DATABASE_NAME}?retryWrites=true&w=majority
      auto-index-creation: false
  application:
    name: "CryptoCurrency Wallet"


logging:
  file:
    name: ./logs/app.log

# Swagger
springdoc:
  api-docs:
    enabled: true
    path: docs
  swagger-ui:
    path: swagger
    operations-sorter: method
  show-actuator: true



# Nodes
utxo:
  nodes:
    TEST_BITCOIN:
      scheme: http
      host: ${BITCOIN_RPC_HOST}
      port: ${BITCOIN_RPC_PORT}
      username: ${BITCOIN_RPC_USERNAME}
      password: ${BITCOIN_RPC_PASSWORD}