# Service Config
server:
  address: 0.0.0.0
  port: ${PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /api
  forward-headers-strategy: native

# GraphQL
graphql:
  servlet:
    enabled: true
    mapping: /graphql
    subscriptions:
      websocket:
        path: /subscriptions
    corsEnabled: false

graphiql:
  enabled: true
  endpoint: /graphql
  mapping: /graphiql
  cdn:
    enabled: false
    version: latest

# MongoDB Config
spring:
  data:
    mongodb:
      uri: mongodb+srv://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${DATABASE_NAME}?retryWrites=true&w=majority
      auto-index-creation: false


# Swagger
springdoc:
  api-docs:
    enabled: true
    path: docs
  swagger-ui:
    path: swagger
    operations-sorter: method
  show-actuator: true

# Nodes
bitcoin:
  rpcScheme: http
  rpcHost: ${BITCOIN_RPC_HOST}
  rpcPort: ${BITCOIN_RPC_PORT}
  rpcUsername: ${BITCOIN_RPC_USERNAME}
  rpcPassword: ${BITCOIN_RPC_PASSWORD}

