apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "utxo-wallet-service.fullname" . }}
  labels:
      {{- include "utxo-wallet-service.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secrets.objectName | squote }}
        objectType: "secretsmanager"
        jmesPath: {{- toYaml $.Values.secrets.objects | nindent 10 }}
  secretObjects:
    - secretName: {{ include "utxo-wallet-service.fullname" . }}
      type: Opaque
      data: {{- toYaml $.Values.secrets.env | nindent 8 }}
